### ISSUE TITLE
Pip install not working

### ISSUE THREAD

**Issue by MaxvandenBoom** [msel-source/pymef#30]
Hey guys,

It seems that `pip install pymef` is broken. I tried it in PyCharm on a new empty project, with a fresh and working Python 3.10.2 install.
It happens both in Windows (Visual studio 2022):
```
PS C:\Users\m_user\PycharmProjects\N1Detect> pip install pymef
Collecting pymef
  Using cached pymef-1.3.2.tar.gz (37 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in c:\users\m_user\pycharmprojects\n1detect\venv\lib\site-packages (from pymef) (1.22.1)
Building wheels for collected packages: pymef
  Building wheel for pymef (pyproject.toml) ... error
  error: subprocess-exited-with-error
                                     
  × Building wheel for pymef (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      running bdist_wheel
      running build
      running build_py
      running build_ext
      building 'pymef.mef_file.pymef3_file' extension
      cl : Command line warning D9002 : ignoring unknown option '-O3'
      pymef3_file.c
      pymef/mef_file/pymef3_file.c(27): fatal error C1083: Cannot open include file: 'pymef3_file.h': No such file or directory
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.30.30705\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pymef
Failed to build pymef
ERROR: Could not build wheels for pymef, which is required to install pyproject.toml-based projects
```

and on the Mac (Clang):

```
(venv) R5194199:henk m_user$ pip install pymef
Collecting pymef
  Downloading pymef-1.3.2.tar.gz (37 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting numpy
  Using cached numpy-1.22.1-cp310-cp310-macosx_10_9_x86_64.whl (17.7 MB)
Building wheels for collected packages: pymef
  Building wheel for pymef (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/m_user/PycharmProjects/henk/venv/bin/python /Users/m_user/PycharmProjects/henk/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/qw/9yt_g6td5t94gd99lhnjx31hzj7v99/T/tmpz3_0n37m
       cwd: /private/var/folders/qw/9yt_g6td5t94gd99lhnjx31hzj7v99/T/pip-install-9u5r8fad/pymef_d66732371eb640c1935b91e2b25d2535
  Complete output (10 lines):
  running bdist_wheel
  running build
  running build_py
  running build_ext
  building 'pymef.mef_file.pymef3_file' extension
  pymef/mef_file/pymef3_file.c:27:10: fatal error: 'pymef3_file.h' file not found
  #include "pymef3_file.h"
           ^~~~~~~~~~~~~~~
  1 error generated.
  error: command '/usr/bin/clang' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for pymef
Failed to build pymef
ERROR: Could not build wheels for pymef which use PEP 517 and cannot be installed directly
```

`python setup.py install` does work, but I guess most people will prefer the `pip` installer

Best,
Max

**Comment by cimbi** [comment]
Hi Max,
it is not broken but it is not precompiled for python 3.10 (the last one is 3.9). It is an easy fix, I'll try to do that tommorw.

**Comment by MaxvandenBoom** [comment]
Hey Jan, I didn't know the compiles were so version specific?! Thanks!

**Comment by cimbi** [comment]
Pymef for python 3.10 should be available via pip now

**Comment by MaxvandenBoom** [comment]
Just to verify, it works again (with `pip`), tnx!

**Comment by tjr1** [comment]
I ran into the same problem installing pymef using python 3.11, so then I tried 3.9.17, and it still didn't work.  
I ended up getting it to work with python 3.7.

**Comment by MaxvandenBoom** [comment]
> I ran into the same problem installing pymef using python 3.11, so then I tried 3.9.17, and it still didn't work. I ended up getting it to work with python 3.7.

Hey Tom!

We're currently updating things. I'll check if the latest release will install on 3.9 and 3.11 when we're done!

**Comment by tjr1** [comment]
Hi Max,
Thanks!  You're the best.
Tom

**Comment by MaxvandenBoom** [comment]
@cimbi I think I suspect what the problem is here. According to statistics around 85% of the Mac users are still on MacOS 10 (Catalina).

If I look at the published files in populair packages they all seems to have macosx 11 and 10 included:

https://pypi.org/project/pandas/2.0.3/#files
pandas-2.0.3-cp*-cp*-macosx_**11_0**_arm64.whl
pandas-2.0.3-cp*-cp*-macosx_**10_9**_x86_64.whl

https://pypi.org/project/numpy/1.25.1/#files
numpy-1.25.1-cp*-cp*-macosx_**11_0**_arm64.whl
numpy-1.25.1-cp*-cp*-macosx_**10_9**_x86_64.whl

https://pypi.org/project/matplotlib/3.7.2/#files
matplotlib-3.7.2-cp311-cp311-macosx_**11_0**_arm64.whl
matplotlib-3.7.2-cp311-cp311-macosx_**10_12**_x86_64.whl
matplotlib-3.7.2-cp311-cp311-macosx_**10_12**_universal2.whl

In contrast to our pymef packages:
https://pypi.org/project/pymef/1.3.6/#files
pymef-1.3.6-cp*-cp*-macosx_**11_0**_x86_64.whl

Probably 85% of the Mac users encounter a situation where pip needs to rebuild it (which only works if you have development tools installed), because there is no MacOS 10 compile available.

I have limited experience with compiling it on different platforms but you seem to have automatized a bunch, do you think it woud be easy to include a compile for MacOS 10.9 as well?

Best,
Max

**Comment by cimbi** [comment]
Good catch, I just hastily stopped the deployment. I will add macOS 10 then. I will ping @tjr1 once the new version is out

**Comment by cimbi** [comment]
Ok, it might be a problem. See here:
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

I can at least try macOS 11

**Comment by MaxvandenBoom** [comment]
> Ok, it might be a problem. See here: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
> 
> I can at least try macOS 11

Hmm, that sad that they don't offer MacOS10.
I wonder how the other packages (like numpy) do it?

**Comment by cimbi** [comment]
They likely use different CI provider

**Comment by MaxvandenBoom** [comment]
@cimbi Works like a charm for me after https://github.com/msel-source/pymef/pull/37, thanks!

@tjr1 Jan updated the release (available through pip) to version 1.4.1.
Would you be willing to see if that works on Python 3.11 (or any >= 3.8) for you?

**Comment by SweetVlad** [comment]
on **macOS 13.5 (arm64)**.

 I don't know if it is related, pip install doesn't work (tested with python3.9). 

Can this be the problem?

Building from source on macOS13.5 with clang v14.0.3 needs cmd arg `-Wno-error=implicit-function-declaration` to suppress errors like:

```
pymef/mef_file/pymef3_file.c:5084:3: error: call to undeclared function 'free_meflib'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                free_meflib();
```
after adding `-Wno-error=implicit-function-declaration` to setup.py
  ```
  MEF_FILE_EXT = Extension("pymef.mef_file.pymef3_file",
                           ["pymef/mef_file/pymef3_file.c"],
                           include_dirs=["meflib/meflib"],
                           extra_compile_args=['-O3', '-Wno-error=implicit-function-declaration'])
  ```
I successfully installed pymef from local source with pip install .

@cimbi @MaxvandenBoom  do you see these errors on ubuntu/win?

**Comment by MaxvandenBoom** [comment]
@SweetVlad Hey Vlad! Let's find out what's happening.

It seems likely that the meflib dependency is not on the latest version, that's why it can't find free_meflib.
I'm not sure, but it seems that you're might be compiling instead of snapping to one of the pre-compiled versions.

So you're in the terminal and executed `pip install pymef`? What happens then? Could you share the full output?
So for me, it gives:
```
(venv) PS C:\Users\abcdef\PycharmProjects\pythonProject> pip install pymef
Collecting pymef
  Using cached pymef-1.4.1-cp38-cp38-win_amd64.whl (100 kB)
Collecting numpy
  Using cached numpy-1.24.4-cp38-cp38-win_amd64.whl (14.9 MB)
Installing collected packages: numpy, pymef
Successfully installed numpy-1.24.4 pymef-1.4.1
```
It's kind of important to see if it takes .whl file or whether it starts compiling something.

Best,
Max

PS. Feel free to e-mail as well if you don't want to share the console output publicly

**Comment by SweetVlad** [comment]
@MaxvandenBoom correct, pip doesn't have precompiled versions.
 Here is the output:
```
Collecting pymef
  Using cached pymef-1.3.6.tar.gz (38 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy (from pymef)
  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/0f/a8/5057b97c395a710999b5697ffedd648caee82c24a29595952d26bd750155/numpy-1.25.2-cp39-cp39-macosx_11_0_arm64.whl.metadata
  Using cached numpy-1.25.2-cp39-cp39-macosx_11_0_arm64.whl.metadata (5.6 kB)
Using cached numpy-1.25.2-cp39-cp39-macosx_11_0_arm64.whl (14.0 MB)
Building wheels for collected packages: pymef
  Building wheel for pymef (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pymef (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-11.1-arm64-cpython-39
      creating build/lib.macosx-11.1-arm64-cpython-39/pymef
      copying pymef/mef_session.py -> build/lib.macosx-11.1-arm64-cpython-39/pymef
      copying pymef/__init__.py -> build/lib.macosx-11.1-arm64-cpython-39/pymef
      copying pymef/mef_constants.py -> build/lib.macosx-11.1-arm64-cpython-39/pymef
      creating build/lib.macosx-11.1-arm64-cpython-39/pymef/mef_file
      copying pymef/mef_file/__init__.py -> build/lib.macosx-11.1-arm64-cpython-39/pymef/mef_file
      running build_ext
      building 'pymef.mef_file.pymef3_file' extension
      creating build/temp.macosx-11.1-arm64-cpython-39
      creating build/temp.macosx-11.1-arm64-cpython-39/pymef
      creating build/temp.macosx-11.1-arm64-cpython-39/pymef/mef_file
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/M186560/opt/anaconda3/envs/spyder310/test_pymef/include -arch arm64 -I/Users/M186560/opt/anaconda3/envs/spyder310/test_pymef/include -fPIC -O2 -isystem /Users/M186560/opt/anaconda3/envs/spyder310/test_pymef/include -arch arm64 -Imeflib/meflib -I/private/var/folders/h_/nzc7wcq54mb11k4fzlj7tpxr0000gq/T/pip-build-env-t07rnwny/overlay/lib/python3.9/site-packages/numpy/core/include -I/Users/M186560/opt/anaconda3/envs/spyder310/test_pymef/include/python3.9 -c pymef/mef_file/pymef3_file.c -o build/temp.macosx-11.1-arm64-cpython-39/pymef/mef_file/pymef3_file.o -O3
      pymef/mef_file/pymef3_file.c:27:10: fatal error: 'pymef3_file.h' file not found
      #include "pymef3_file.h"
               ^~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pymef
Failed to build pymef
ERROR: Could not build wheels for pymef, which is required to install pyproject.toml-based projects
```

**Comment by MaxvandenBoom** [comment]
It seems to me it wants to use an older cached version of pymef (1.3.6), the latest is 1.4.1
Could you try `pip install --upgrade pymef` for me and see what that does and share the output?

**Comment by SweetVlad** [comment]
```
 pip install pymef==1.4.1
ERROR: Could not find a version that satisfies the requirement pymef==1.4.1 (from versions: 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6)
ERROR: No matching distribution found for pymef==1.4.1
```
and `pip install --upgrade pymef` gives the same result as `pip install pymef`

**Comment by MaxvandenBoom** [comment]
That's suspicious... `https://pypi.org/project/pymef/` definitely seems to have 1.4.1, and - if I understand correctly - should retrieve that even if it has to build.

Are you sure it's trying to retrieve packages from the normal python repo?
Could you try `pip install --upgrade --verbose pymef`, maybe that gives more info

**Comment by SweetVlad** [comment]
I see the problem 1.4.1. doesn't have the matching compiled version  and is also missing the source files tar.gz
1.3.6 has the source files on pip.

**Comment by MaxvandenBoom** [comment]
I think you're right, nice find Vlad!!
Out of curiosity, did the verbose show any of that?

___
I guess this is something for Jan to fix.
@cimbi Do you think it is possible to upload the source distribution of 1.4.1 as well, besides it's wheel files

See: [https://pypi.org/project/pymef/1.3.6/#files](https://pypi.org/project/pymef/1.3.6/#files)
There is a `Source Distribution` header that includes the `pymef-1.3.6.tar.gz`
which is missing on: [https://pypi.org/project/pymef/1.4.1/#files](https://pypi.org/project/pymef/1.4.1/#files)
I think Python `build` produces that, so you probably can append just that file to the current version.

___
I also just inspected the contents of `pymef-1.3.6.tar.gz` and found the cause of the bug we (at least me, Vlad and perhaps also Tom) are having when trying to build: `Cannot open include file: 'pymef3_file.h': No such file or directory` (see my compile output at the top of this issue and Vlad's).

After unpacking `pymef-1.3.6.tar.gz`, you can see the source distribution is missing a number of files, amongst which `pymef3_file.h`, causing the compile error. Also the entire meflib is missing from that source distribution, which is needed to compile.
@cimbi Maybe we can fix all of this in one go when we upload the source distribution for version 1.4.1?

**Comment by cimbi** [comment]
I think I know where I made a mistake - I switched to older Mac OS version as per the above comment (https://github.com/msel-source/pymef/issues/30#issuecomment-1658239427). I will add the newer version to the CI matrix too. But I'd like to wait until we resolve #38 .

**Comment by tjr1** [comment]
Yes, the missing C++ mef library is a problem for those installing pymef from source code.  Looks like you have a symbolic link to the library on your computer, so it doesn't throw an error when you build it locally.  Would the missing C++ files be a problem if using a github hosted runner?

And about MacOs 10.9: 
Another reason to stay compatible with MacOs 10.9 is that the python runtime distributed with conda is built for 10.9, and therefore even Macs running 11 or 12 still need 10.9 if they are using conda.  I learned this when sorting out dhn-med-py pip installer.

**Comment by MaxvandenBoom** [comment]
Wow tom, I never knew conda still hung onto 10.9

Not sure if this adds any, but meflib is a submodule in pymef, and the tests do show inclusion in their runnings:
```
Run auth_header="$(git config --local --get http.https://github.com/.extraheader)"
Submodule 'meflib' (https://github.com/msel-source/meflib.git) registered for path 'meflib'
Cloning into '/home/runner/work/pymef/pymef/meflib'...
Submodule path 'meflib': checked out 'e955aa0b582737ecd26e6f9f11489ccfd2c94de4'
```

**Comment by cimbi** [comment]
@tjr1 and @MaxvandenBoom

The dependence of conda on 10.9 is a bit of a problem because MacOS 10 runner was deprecated from github runners on 8/30/22. See here: https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/. A solution would be to use third party CI but it is a pain to setup.
The relevant discussion from the conda team is here:
https://github.com/conda-forge/conda-forge.github.io/issues/1844

**Comment by MaxvandenBoom** [comment]
Interesting, that topic mentions stats (from one month ago) on one million Pillow package downloads: 98.35% are on >=11.0
No wonder github is deprecating, and surprising Conda will still be stuck on a minimum of 10.13
And I guess the webstats that I mentioned before are off because some browsers still pretend to be on an older MacOS.



I think keeping our runners on MacOS11 and MacOS12 (latest) makes most sense.
As long as we include the source distribution with the next release, then conda will just automatically build the wheel itself.

**Comment by MaxvandenBoom** [comment]
@cimbi I saw you released 1.4.2, nice!!

However, I think the Source Distribution is still missing:
[https://pypi.org/project/pymef/1.4.2/#files](https://pypi.org/project/pymef/1.4.2/#files)
(is missing `pymef-1.4.2.tar.gz`)

As a result, compiling will still revert to 1.3.6, since that is the latest packages that does include the source distribution:
[https://pypi.org/project/pymef/1.3.6/#files](https://pypi.org/project/pymef/1.3.6/#files)
(has `pymef-1.3.6.tar.gz`)

It should simply be a matter of only adding/uploading the file: 
`pymef-1.4.2.tar.gz`

Also, before uploading, we should make sure the header files of meflib and pymef are included in the tar file. These files are missing in 1.3.6 and will break an automatic compile if there is no wheel present.

**Comment by samoelelo** [comment]
I'm having the same issue, were you able to fix it?

I've tried with multiple python and pymef versions but it didn't work, I also tried using *python setup.py install* but there results weren't different. I'm using MacOs 14.7.1 and always get the same error:
This whit PIP:
![Screenshot 2024-12-16 at 11 11 45 AM](https://github.com/user-attachments/assets/a3140441-655e-4a6f-95c3-fd25f71932a9)


This whit python setup.py install:

![Screenshot 2024-12-16 at 11 08 13 AM](https://github.com/user-attachments/assets/e4ba1ab7-c620-484f-a4d9-212beeddb578)

**Comment by MaxvandenBoom** [comment]
It was fixed, but I can take another look.

Could you report which version of PyMef your install is trying to build? (can't see it in the console screens you added)
